# Generated by Django 6.1 on 2026-08-21 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0004_category_translations_place_translations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViatorProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(help_text="Viator's productCode, e.g. '5010SYDNEY'", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viator_products', to='places.place')),
            ],
            options={
                'ordering': ['place', 'product_code'],
                'unique_together': {('place', 'product_code')},
            },
        ),
    ]
