# Generated by Django 6.1 on 2026-08-20 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='image',
        ),
        migrations.AddField(
            model_name='place',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
