# Generated by Django 6.1 on 2026-08-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_image_credit_place_image_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text='{"ja": {"name": ...}, "ne": {...}, "hi": {...}}'),
        ),
        migrations.AddField(
            model_name='place',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text='{"ja": {"name": ..., "description": ...}, "ne": {...}, "hi": {...}}'),
        ),
    ]
