# Generated by Django 6.1 on 2026-08-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_remove_destination_image_destination_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='interest_tags',
            field=models.JSONField(blank=True, default=list, help_text='List of users.TravelPreference.Interest values this destination matches'),
        ),
    ]
