# Generated by Django 6.1 on 2026-08-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_destination_interest_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image_credit',
            field=models.CharField(blank=True, help_text='Photographer/author and license, e.g. "Jane Doe — CC BY-SA 4.0"', max_length=255),
        ),
        migrations.AddField(
            model_name='destination',
            name='image_source',
            field=models.CharField(blank=True, help_text='e.g. "Wikimedia Commons"', max_length=100),
        ),
        migrations.AddField(
            model_name='destination',
            name='image_source_url',
            field=models.URLField(blank=True, help_text='Page the image was verified/sourced from'),
        ),
    ]
