# Generated by Django 6.1 on 2026-08-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_destination_image_credit_destination_image_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text='{"ja": {"name": ..., "description": ...}, "ne": {...}, "hi": {...}} — the base name/description fields remain the English source of truth.'),
        ),
    ]
