# Generated by Django 6.1 on 2026-08-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpreference',
            name='preferred_currency',
            field=models.CharField(blank=True, help_text='ISO 4217 code, e.g. "JPY" — optional, never required', max_length=3),
        ),
    ]
